// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Describe(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadAtmosData(arg1:string):Promise<Array<main.StackComponent>>;

export function PickConfigFile():Promise<string>;

export function RunTerraform(arg1:string,arg2:string,arg3:string):Promise<string>;
