// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PickConfigFile() {
  return window['go']['main']['App']['PickConfigFile']();
}

export function LoadAtmosData(arg1) {
  return window['go']['main']['App']['LoadAtmosData'](arg1);
}

export function Describe(arg1, arg2) {
  return window['go']['main']['App']['Describe'](arg1, arg2);
}

export function RunTerraform(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunTerraform'](arg1, arg2, arg3);
}
